<a href="https://colab.research.google.com/github/guymercier/Pytoroch-Tutoriel-2023-07-10/blob/main/Intro_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [7]:
# !pip list

In [8]:
import numpy as np

In [11]:
# liste

ma_liste = [[1,2,3,4,5], [6,7,8,9,10]]

ma_liste

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [12]:
# numpy_array

np1 = np.random.rand(3,4)
np1

array([[0.19291576, 0.57904762, 0.63029092, 0.27292698],
       [0.62488882, 0.89791049, 0.58464275, 0.67045176],
       [0.66401149, 0.25221657, 0.85933626, 0.24042947]])

In [13]:
np1.dtype

dtype('float64')

In [14]:
# tensors

tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.0912, -1.4264, -1.6179,  0.5472],
        [ 1.1911, -0.6091, -0.1398,  0.0300],
        [ 0.3616,  0.3384,  0.4209, -0.2837]])

In [16]:
tensor_3d = torch.zeros(3,4,5)
tensor_3d

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [17]:
 # Create tensor out of numpy array

mon_tensor = torch.tensor(np1)
mon_tensor

tensor([[0.1929, 0.5790, 0.6303, 0.2729],
        [0.6249, 0.8979, 0.5846, 0.6705],
        [0.6640, 0.2522, 0.8593, 0.2404]], dtype=torch.float64)